---
title: "BRIGHTEN - Data Prep"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
library(data.table)
library(gdata)
library(synapseClient)
synapseLogin()
library(ggplot2)
library(plyr)
library(dplyr)
library(tidyr)
library("reshape2")
library("knitr")
library("ggpubr")
library("ggthemes")
options(stringsAsFactors = F,
        Sys.setenv(TZ='GMT'))

knitr::opts_chunk$set(echo = F,  message=FALSE, warning=FALSE)
knitr::opts_chunk$set(comment = NA, results = "asis", comment = NA, tidy = F)
```



```{r}
#PHQ9
phq9 <- read.xls(synGet('syn10250492')@filePath)
phq9 <- phq9 %>% mutate(phq10 = as.numeric(  as.character(plyr::revalue(phdis, replace=c('Not difficult at all' = 0, 'Somewhat difficult' = 1, 'Very difficult' = 2,
          'Extremely difficult'=3))))) %>%
  mutate(sum_phq9 = phq9, start =lubridate::ymd(start)) %>% 
  mutate(sum_phq10 = sum_phq9 + phq10,
         study_arm = gsub('-.*','',brightenid),
         phq9ResponseTimeSecs = as.numeric(lubridate::ymd_hms(response_utc) - lubridate::ymd_hms(sent_time_utc))) %>% select(user_id, brightenid, study_arm, start, week, phq9ResponseTimeSecs, sum_phq9, sum_phq10)


#PHQ2
phq2 <- read.xls(synGet('syn10250486')@filePath)
phq2$sum_phq2 = rowSums(phq2[,c(10,11)])
phq2[,c(9,10,11,12)] <- NULL
phq2 <- phq2 %>%  
  mutate(phq2_date_local = as.Date(lubridate::ymd_hms(sent_time_local)),
         day = day + 1,
         start = lubridate::ymd(start),
         phq2ResponseTimeSecs = as.numeric(lubridate::ymd_hms(response_utc) - lubridate::ymd_hms(sent_time_utc))) %>% 
  select(user_id, phq2_date_local, start, day, phq2ResponseTimeSecs, sum_phq2)


#GingerIO data
passive_data <- fread(synGet('syn5908849')@filePath, data.table = F)
colnames(passive_data) <- tolower(gsub(' ', '_',colnames(passive_data)))
passive_data <- passive_data  %>% mutate(passive_date_pacific = as.Date(lubridate::ymd_hms(start))) %>%  
  select(-end, -start)
#getting the participant start dates from PHQ2 data
passive_data <- merge(passive_data, phq2_start_dates, all.x = T)

passive_metadata <- fread(synGet('syn5908850')@filePath, data.table = F)
colnames(passive_metadata) <- gsub(' ', '_',colnames(passive_metadata))
passive_metadata <- passive_metadata %>% mutate(brightenid = Participant_ID) %>%
  select(-SMS_Count, -Location_Count, -Call_Count, -Participant_ID, -Timezone_at_Activation , -Participant_ID, -Survey_Completion_Percentage,
-Group, -Profile_ID, -Activation_Status)
passive_metadata['activation_date_local'] = passive_metadata['Activation_Date_(Local)']
passive_metadata['activation_date_UTC'] = passive_metadata['Activation_Date_(UTC)']
passive_metadata['Activation_Date_(Local)'] <- NULL
passive_metadata['Activation_Date_(UTC)'] <- NULL
passive_metadata <- passive_metadata %>% 
  mutate(activation_date_local = as.Date(lubridate::ymd_hms(activation_date_local)),
         activation_date_UTC = as.Date(lubridate::ymd_hms(activation_date_UTC)))
passive_data <- merge(passive_data, passive_metadata, all.x=T)


#### $NOTE$
# The following code tells us that "activation_date_UTC" is the best column for # assuming the actual study start date across activities for individuals
####
# phq9_start_dates <- phq9 %>% select(user_id, start) %>% mutate(phq9_start = start) %>% select(-start)
# phq9_start_dates <- phq9_start_dates[!duplicated(phq9_start_dates),] 
# phq2_start_dates <- phq2 %>% select(user_id, start) %>% mutate(phq2_start = start) %>% select(-start)
# phq2_start_dates <- phq2_start_dates[!duplicated(phq2_start_dates),]
# passive_start_dates <- passive_data %>% select(user_id, activation_date_local, activation_date_UTC)
# passive_start_dates <- passive_start_dates[!duplicated(passive_start_dates),]
# x <- merge(merge(phq2_start_dates, phq9_start_dates, all=T),passive_start_dates, all=T )
# x['diff'] = x$activation_date_local - x$activation_date_UTC
# View(x)

passive_data <- passive_data %>% 
  dplyr::mutate(day = as.numeric(passive_date_pacific-activation_date_UTC) + 1 ,
                week = ((day - 1) %/% 7) + 1 ) %>%
  dplyr::mutate(start = activation_date_UTC)  %>%
  dplyr::select(-activation_date_local, -activation_date_UTC, -phq2_start )

#Study metadata
study_metadata <- read.xls(synGet('syn10250485')@filePath)
study_metadata <- study_metadata %>% 
  dplyr::mutate(brightenid = as.character(brightenid),
                baseline_phq9 = PHQScore) %>%
  dplyr::select(-c(21:27, 36:43), -PHQScore)
  
#remove rows with >50 % missing meta data
to_keep <- apply(study_metadata, 1, function(row) ( sum( is.na(row)) + sum(row == '', na.rm = T)) / length(row)) < .50
study_metadata <-study_metadata[to_keep,]

# extract master table user_id to brightenid
userId_to_brigthenId <- rbind(phq9 %>% select(user_id, brightenid), 
                              passive_data %>% select(user_id, brightenid))
      
userId_to_brigthenId <- userId_to_brigthenId[!duplicated(userId_to_brigthenId),]

#add user-id to study metadata table
study_metadata <- merge(userId_to_brigthenId, study_metadata, all.y = T)

#add user-id to study metadata table
phq2 <- merge(userId_to_brigthenId, phq2, all.y = T)
```


```{r}
replace_codes <- c('BLUE' = 'iPST', 'ORANGE' = 'Health Tips', 'GREEN' = 'Akili',
                   'RED' = 'EVO_on_iphone_only', 'YELLOW' = 'HealthTips_on_Android')
phq9$study_arm <- plyr::revalue(phq9$study_arm, replace = replace_codes)
study_metadata <- study_metadata %>% dplyr::mutate(study_arm = plyr::revalue(Studygroup, replace = replace_codes)) %>% dplyr::select(-Studygroup)
```


```{r}
#filter days in passive data where no passive feature is recorded  
select_cols <- colnames(passive_data)[2:11]
to_keep <- apply(passive_data[, select_cols], 1, function(row) (sum(is.na(row)) + sum(row == '', na.rm = T)) < length(row))
passive_data <- passive_data[to_keep,]

#add study grp to PHQ2
phq2 <- merge(phq2, study_metadata[,c('user_id','study_arm')])

### Add study arm info in ginger data
temp_df <- rbind(phq9[,c('user_id','study_arm')],
                 study_metadata[, c('user_id', 'study_arm')])
temp_df <- temp_df[!duplicated(temp_df),]
passive_data <- merge(passive_data, temp_df, all.x=T)
passive_data <- passive_data %>% mutate(study_arm = as.factor(study_arm))
```

```{r}
###upload the cleaned data to synapse
parentId <- "syn10236537"

#Passive data
outFile = "BRIGHTEN_V1_passive_features.tsv"
write.table(passive_data, file=outFile, sep="\t", col.names=T, row.names=F)
synStore(File(outFile, parentId = parentId),
         used = c("syn5908849", "syn5908850"),
         executed = "https://github.com/apratap/BRIGHTEN-Study/blob/master/dataPrep.Rmd")
unlink(outFile)

#phq2
outFile = "BRIGHTEN_V1_phq2_scores.tsv"
write.table(phq2, file=outFile, sep="\t", col.names=T, row.names=F)
synStore(File(outFile, parentId = parentId),
         used = "syn10250486",
         executed = "https://github.com/apratap/BRIGHTEN-Study/blob/master/dataPrep.Rmd")
unlink(outFile)

#phq9
outFile = "BRIGHTEN_V1_phq9_scores.tsv"
write.table(phq9, file=outFile, sep="\t", col.names=T, row.names=F)
synStore(File(outFile, parentId = parentId),
          used ="syn10250492",
         executed = "https://github.com/apratap/BRIGHTEN-Study/blob/master/dataPrep.Rmd")
unlink(outFile)

#study metadata
outFile = "BRIGHTEN_V1_study_metadata.tsv"
write.table(study_metadata, file=outFile, sep="\t", col.names=T, row.names=F)
synStore(File(outFile, parentId = parentId),
         used="syn10250485",
         executed = "https://github.com/apratap/BRIGHTEN-Study/blob/master/dataPrep.Rmd")
unlink(outFile)
```




```{r}

# dim(x)
# y <- passivefeatures %>% filter(user_id == '10439')
# dim(y)
# dim(merge(x,y, by.x=c('user_id', 'phq2ResponseDate'), 
#            by.y=c('user_id', 'passiveFeatureDate')))
# 

# passivefeatures <- gingerio_data
# mdata <- study_metadata
# 
# ### For now we are averaging over PHQ2 scores over 3 days. (+/- 1 day from passive data entry)
# boundary_days <- 1
# tmp_phq2 <- phq2 %>% as.data.frame() %>% 
#   mutate(tmp_epoch_min = as.numeric(as.POSIXct(phq2ResponseDate, tz="UTC")) + (boundary_days*24*60*60),
#          #tmp_epoch_max = as.numeric(as.POSIXct(phq2ResponseDate, tz="UTC")) + (boundary_days*24*60*60),
#          tmp_epoch_max = as.numeric(as.POSIXct(phq2ResponseDate)) + (boundary_days*24*60*60),
#          phq2Response_epoch = as.numeric(as.POSIXct(phq2ResponseDate, tz="UTC"))) %>% 
#   select(user_id, tmp_epoch_min, tmp_epoch_max, phq2Response_epoch, phq2ResponseDate, sum_phq2)
# 
# tmp_passiveFeatures <- passivefeatures %>% 
#   mutate(passiveFeatureDate_epoch = as.numeric(as.POSIXct(passiveFeatureDate , tz="UTC"))) %>% select(-study_arm)
# 
# library(sqldf)
# phq2_passiveFeatures <- sqldf('select * from tmp_passiveFeatures inner join tmp_phq2 on tmp_passiveFeatures.user_id == tmp_phq2.user_id where tmp_passiveFeatures.passiveFeatureDate_epoch between tmp_phq2.tmp_epoch_min and tmp_phq2.tmp_epoch_max')
# phq2_passiveFeatures$user_id <- NULL
# phq2_passiveFeatures <- phq2_passiveFeatures %>%
#                         group_by(user_id, passiveFeatureDate, SMS_Length, Unreturned_Calls, Call_Duration,     Mobility, Interaction_Diversity, Missed_Interactions, Aggregate_Communication, SMS_Count,
#                                 Mobility_Radius, Call_Count, day_in_study, week_in_study) %>% 
#   summarise(sum_phq2 =mean(sum_phq2, na.rm = T))


########################
# MERGE - baseline demographics
########################=
# phq2_passiveFeatures_demog <- phq2_passiveFeatures %>% inner_join(mdata %>% mutate(user_id = as.character(user_id)) %>%
#                                            select(user_id, Gender, Age, PHQScore, State, education, employed,
#                                                           income1, income2, marital, race, ordinalincome, minority,
#                                                           therapist, book))

#upload to synapse
# write.table(phq2_passiveFeatures_demog, file="phq2_passive_demog_integrated.tsv", sep="\t",row.names = F, quote=F, col.names = T)
# tmp = synStore(File("phq2_passive_demog_integrated.tsv", parentId = 'syn7211114'),
#                used = c('syn8259883', 'syn8259868', 'syn8259866'),
#                executed = "https://github.com/apratap/BRIGHTEN-Study/blob/master/dataPrep.Rmd")
# unlink("phq2_passive_demog_integrated.tsv")

################
#MERGE PHQ9
################

# boundary_days <- 3
# tmp_phq9 <- phq9  %>% 
#   mutate(tmp_epoch_min = as.numeric(as.POSIXct(phq9ResponseDate, tz="UTC")) - (boundary_days*24*60*60),
#          tmp_epoch_max = as.numeric(as.POSIXct(phq9ResponseDate, tz="UTC")) + (boundary_days*24*60*60)) %>%
#   select(user_id, phq9ResponseDate, tmp_epoch_min, tmp_epoch_max, ph1,ph2,ph3,ph4,ph5,ph6,ph7,ph8,ph9,sum_phq9) %>% filter(user_id %in% phq2_passiveFeatures$user_id)
# 
# dim(passivefeatures)
# tmp_phq2_passiveFeatures <- phq2_passiveFeatures_demog %>% mutate(passiveFeatureDate_epoch = as.numeric(as.POSIXct(passiveFeatureDate, tz="UTC")))
# 
# 
# library(sqldf)
# phq2_passive_ph9_demog <- sqldf('select * from tmp_phq9 inner join tmp_phq2_passiveFeatures on tmp_phq2_passiveFeatures.user_id == tmp_phq9.user_id where tmp_phq2_passiveFeatures.passiveFeatureDate_epoch between tmp_phq9.tmp_epoch_min and tmp_phq9.tmp_epoch_max')
# phq2_passive_ph9_demog$user_id <- NULL
# phq2_passive_ph9_demog <- phq2_passive_ph9_demog %>% select(-passiveFeatureDate_epoch, -tmp_epoch_min, -tmp_epoch_max, -passiveFeatureDate, -State, -income2)
# 
# phq2_passive_ph9_demog <- phq2_passive_ph9_demog %>% group_by(user_id, Gender, Age, PHQScore, education, employed, 
#                                                   income1, marital, race, ordinalincome,
#                                                   minority, therapist, book, 
#                                                   phq9ResponseDate, ph1, ph2, ph3, ph4, ph5, ph6, ph7, ph8, ph9, sum_phq9) %>%
#                     summarise_each(funs(median))


#upload to synapse
# write.table(phq2_passive_ph9_demog, file="phq2_passive_phq9_demog_integrated.tsv", sep="\t",row.names = F, quote=F, col.names = T)
# tmp = synStore(File("phq2_passive_phq9_demog_integrated.tsv", parentId = 'syn7211114'),
#                executed = "https://github.com/apratap/BRIGHTEN-Study/blob/master/dataPrep.Rmd")
#unlink("phq2_passive_phq9_demog_integrated.tsv")
```
